# -*- coding: utf-8 -*-
"""EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xzUDiltP-WCaPo1MLBtHUT9vtBLa8wJB
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Set a random seed for reproducibility
np.random.seed(42)
num_customers = 500

# Generate synthetic numerical data
# Age: realistic distribution
ages = np.random.randint(18, 75, size=num_customers)
# Satisfaction Score: scaled from 1 to 10
satisfaction_scores = np.random.randint(1, 11, size=num_customers)
# Purchase Frequency: 1 to 30 times a year
purchase_frequency = np.random.randint(1, 31, size=num_customers)

# Generate synthetic categorical data (Region)
regions = np.random.choice(['North', 'South', 'East', 'West'],
                           size=num_customers,
                           p=[0.3, 0.25, 0.25, 0.2])

# Create the DataFrame
df = pd.DataFrame({
    'Age': ages,
    'Satisfaction Score': satisfaction_scores,
    'Purchase Frequency': purchase_frequency,
    'Region': regions
})

print("--- Synthetic Data Head ---")
print(df.head())
print("\n--- Data Info ---")
print(df.info())
#2. Descriptive Statistics

df.describe()
print("\n--- Descriptive Statistics (Numerical) ---")
print(df[['Age', 'Satisfaction Score', 'Purchase Frequency']].describe())

print("\n--- Frequency Count (Categorical) ---")
print(df['Region'].value_counts())
#3. Basic Data Visualization
#Distribution of Age (Histogram)
plt.figure(figsize=(8, 5))
sns.histplot(df['Age'], kde=True, bins=20)
plt.title('Distribution of Customer Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

#Satisfaction Score by Region (Box Plot)

plt.figure(figsize=(10, 6))
sns.boxplot(x='Region', y='Satisfaction Score', data=df)
plt.title('Box Plot of Satisfaction Score by Region')
plt.xlabel('Region')
plt.ylabel('Satisfaction Score')
plt.show()
#Correlation Heatmap (Relationships)
# Calculate correlation matrix
correlation_matrix = df[['Age', 'Satisfaction Score', 'Purchase Frequency']].corr()

plt.figure(figsize=(7, 5))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap of Numerical Variables')
plt.show()